[project]
name = "kbputils"
version = "0.0.1"
dependencies = [
    "ass"
]
[project.scripts]
KBPUtils = "kbputils.cli:convert_file"
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[tool.setuptools.packages.find]
include = ["kbputils"]
